### ISSUE TITLE
How to step index forward?

### ISSUE THREAD

**Issue by mrshmllow** [FraserLee/bevy_sprite3d#1]
it seems to be turned into a PbrBundle so i cant figure out how to access the index. Id like to achieve something like https://bevyengine.org/examples/2d/sprite-sheet/

**Comment by FraserLee** [comment]
Just looking back over the code now, I don't think I ever actually implemented this. Will fix this weekend!

**Comment by FraserLee** [comment]
Sorry for not getting around to this sooner! Check out `examples/sprite_sheet.rs` to see how to do it.
