### ISSUE TITLE
Atlas size arbitrarily set to 9?

### ISSUE THREAD

**Issue by dmyyy** [FraserLee/bevy_sprite3d#10]
Is there a reason why atlas size is hardcoded to be 9?

**Comment by FraserLee** [comment]
I assume you're talking about
```

**Comment by dmyyy** [comment]
I was confused by the atlas type in `AtlasSprite3dComponent`. Are the mesh's cached per texture in the texture atlas? They seem to index on the texture width/height (but different textures in the same atlas can have the same width/height etc.)

**Comment by dmyyy** [comment]
If the intention is to create a unique key (which is why I assume `MESH_CACHE_GRANULARITY` is a float) wouldn't it be better to key on `[f32; 9]`?

**Comment by FraserLee** [comment]
We initially retrieve a mesh from a mesh-key (one of the int arrays) by looking it up here
https://github.com/FraserLee/bevy_sprite3d/blob/main/src/lib.rs#L433C17-L433C89

and later an update system swaps it out if we see the index has changed here
https://github.com/FraserLee/bevy_sprite3d/blob/main/src/lib.rs#L77

For any one combo of mesh size, pivot, and UVs, we have only one mesh (cached and reused). A texture atlas currently uses different UVs to represent each sub-texture - hence the array of mesh keys. There might be an optimization to be made here by swapping to a single mesh without UVs - setting UVs via some other data passed into the shader - then we lose out on being able to use bevy's default shaders. Might be worth looking into at some point, but I haven't personally seen performance even close to bottlenecked by the current system.

Does that about answer your question?

**Comment by dmyyy** [comment]
Answers my question - thank you!
