### ISSUE TITLE
Weird behaviour under a 3d camera

### ISSUE THREAD

**Issue by Hakukano** [FraserLee/bevy_sprite3d#4]
https://user-images.githubusercontent.com/22399952/225992560-c1927420-4f9d-4948-b9cd-c742c50b0211.mov

Setup: bevy 0.10 + bevy_sprite3d
Issue: A part of character sprite disappears at some positions

The character and all tiles are individual 3d sprites. The tiles are rotated PI/2 along x axis to make a flat floor. (as shown in the video, the floor is indeed flat)

The character moves along x/z and after passing half of the tile, the lower part of the character disappears. This happens for every single tile.

Other than this issue, everything else works fine, including lighting and shadows.

**Comment by Hakukano** [comment]
Thanks to a guy on Discord, I found that this is an issue of the pivot. I should've put the pivots of tiles to (0.5, 0) before the rotation. Case closed.

**Comment by FraserLee** [comment]
Oh that's a weird one. Glad you managed to solve it!
