### ISSUE TITLE
Using look_at or look_to to make a sprite face directly up makes that sprite dissapear.

### ISSUE THREAD

**Issue by Cassumbra** [FraserLee/bevy_sprite3d#7]
Rotating the sprite straight up manually seems to work fine, but using look_at or look_to seems to cause odd behavior.

**Comment by FraserLee** [comment]
That's interesting. What odd behaviour are you seeing specifically, and is the thing you're trying to look_at the camera?

**Comment by FraserLee** [comment]
If the sprite is disappearing entirely, the two most likely things to mind would be either if you're looking at it edge-on, or if you're looking from behind and `double_sided` is disabled. Possibly also if the pivot is in a weird place, the rotation could be "translating" it to somewhere you can't see - though that's less likely.

**Comment by Cassumbra** [comment]
I don't think its a looking at it edge-on problem. I'm also fairly certain it isnt due to double_sided being disabled, since its enabled by default, and I didn't change it.
I believe I also checked the underside of the sprites, as well.
It could be pivot oddness. I'm not sure. I didn't mess with the pivot, though.

**Comment by FraserLee** [comment]
Huh that is strange. Do you think you could post a minimum reproducible sample?

**Comment by Cassumbra** [comment]
yeah, okay
so basically make a project as simple as possible that causes the issue?

**Comment by FraserLee** [comment]
Yep, exactly

**Comment by FraserLee** [comment]
Closing as inactive. Feel free to reopen if this happens again!
